---
- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: localhost
  gather_facts: no
  tasks:

    - name: DISPLAY THE INJECTED EXTRA VAR
      debug:
        var: secret_key
      debug:
        msg: "secret_key {{ secret_key }}"
    - name: CLONE THE GIT REPO
      git:
        repo: git@github.com:garamirkim/opentest.git
        dest: /tmp/my_test_repo
        key_file: "{{ secret_key  }}"
        accept_hostkey: yes 
        force: yes
      delegate_to: localhost

